//test exception
// Exception in loop condition 

int main ()
{
  int x = 5;
  int res = 0;
  int sum = 2;
  for (int z = 0; (z/0) < x; z++){
    res = res * sum;    
  }
  return res;
}
