//test exception

int main()
{
    int x;
    int y;

    x = 5;
    y = 0;

    return x / y;
}

