//test exception 6

int main() {
    assert(false);
    return 0;
}
