//test exception 8

int main()
{
  int x;
  int y;
  x = 0;
  y = 0 / x;
  return y;
}
