//test exception
int main()
{
        int x = 3/0;
	return x;
}