//test exception 8

int main()
{
	int x;
	int y;
	
	x = 1;
	y = 0;
	
	return x/y;
}
